const response=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const pdfLimit=200*1024*1024;
let schemaReady;
async function ensureSchema(env){
 if(!env.DB)return;
 if(!schemaReady)schemaReady=env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS archives (
    user_id TEXT PRIMARY KEY NOT NULL,
    payload TEXT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1
  )`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS books (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    book_key TEXT NOT NULL,
    name TEXT NOT NULL,
    object_key TEXT NOT NULL
  )`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS shared_campaigns (
    code TEXT PRIMARY KEY NOT NULL,
    payload TEXT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1
  )`)
 ]).catch(error=>{schemaReady=null;throw error;});
 await schemaReady;
}
async function multipartBook(request,env,path,user){const match=path.match(/^\/api\/books\/(base|horror|as[1-7])\/multipart(?:\/([0-9a-f-]{36})\/([^/]+)(?:\/(\d+|complete|abort))?)?$/);if(!match)return null;const [,key,objectId,encodedUploadId,action]=match,bookId=user+':'+key;if(!objectId&&request.method==='POST'){const input=await request.json();if(!input||!Number.isInteger(input.size)||input.size<5||input.size>pdfLimit||typeof input.name!=='string'||!input.name.toLowerCase().endsWith('.pdf'))return response({error:'Escolha um PDF de até 200 MB.'},413);const objectKey=user+'/'+crypto.randomUUID()+'.pdf',upload=await env.FILES.createMultipartUpload(objectKey,{httpMetadata:{contentType:'application/pdf'}});return response({objectId:objectKey.split('/').at(-1).slice(0,-4),uploadId:upload.uploadId});}if(!objectId||!encodedUploadId)return response({error:'Envio inválido.'},400);const objectKey=user+'/'+objectId+'.pdf',upload=env.FILES.resumeMultipartUpload(objectKey,decodeURIComponent(encodedUploadId));if(request.method==='PUT'&&/^\d+$/.test(action||'')){const part=Number(action),size=Number(request.headers.get('content-length'));if(part<1||part>25||!size||size>8*1024*1024||size<5*1024*1024&&request.headers.get('x-last-part')!=='1')return response({error:'Parte do arquivo inválida.'},413);const result=await upload.uploadPart(part,request.body);return response({partNumber:result.partNumber,etag:result.etag});}if(request.method==='POST'&&action==='complete'){const input=await request.json(),parts=input.parts;if(!Array.isArray(parts)||parts.length<1||parts.length>25||!Number.isInteger(input.size)||input.size>pdfLimit||input.size<5||typeof input.name!=='string')return response({error:'Envio inválido.'},400);if(parts.some((p,i)=>p.partNumber!==i+1||typeof p.etag!=='string'||!p.etag))return response({error:'Partes fora de ordem.'},400);await upload.complete(parts);const file=await env.FILES.head(objectKey);if(!file||file.size!==input.size){await env.FILES.delete(objectKey);return response({error:'O PDF chegou incompleto. Tente novamente.'},400);}const old=await env.DB.prepare('SELECT object_key FROM books WHERE id = ? AND user_id = ?').bind(bookId,user).first(),name=input.name.slice(0,200);try{await env.DB.prepare('INSERT INTO books (id,user_id,book_key,name,object_key) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name = excluded.name, object_key = excluded.object_key').bind(bookId,user,key,name,objectKey).run();}catch(error){await env.FILES.delete(objectKey);throw error;}if(old&&old.object_key!==objectKey)await env.FILES.delete(old.object_key);return response({name});}if(request.method==='POST'&&action==='abort'){await upload.abort();return response({ok:true});}return response({error:'Rota inválida.'},404);}
function sharedData(value){
 if(!value||typeof value!=='object')return null;
 const str=(v,max)=>String(v??'').trim().slice(0,max),num=(v,max)=>Math.max(0,Math.min(max,Number(v)||0));
 const sanitizePublicKey=x=>{if(!x||x.kty!=='RSA'||typeof x.n!=='string'||typeof x.e!=='string'||!x.n||!x.e)return null;return{kty:'RSA',n:str(x.n,600),e:str(x.e,12),alg:'RSA-OAEP-256',ext:true,key_ops:['encrypt']};};
 const roster=Array.isArray(value.roster)?value.roster.slice(0,50).map(p=>({id:str(p.id,80),name:str(p.name,60),agent:str(p.agent,70),class:str(p.class,50),nex:str(p.nex,12),publicKey:sanitizePublicKey(p.publicKey)})).filter(p=>p.id&&p.name):[];
 const entries=(key,max)=>Array.isArray(value[key])?value[key].slice(0,max).map(x=>({id:str(x.id,80),title:str(x.title,120),body:str(x.body,4000),owner:str(x.owner,60),created:str(x.created,40),status:str(x.status,30),initiative:Math.max(-99,Math.min(999,Number(x.initiative)||0)),round:Math.max(1,Math.min(999,Number(x.round)||1)),turn:Math.max(0,Math.min(100,Number(x.turn)||0)),summary:str(x.summary,3000),objective:str(x.objective,3000),questions:str(x.questions,3000),clues:str(x.clues,3000),participants:Array.isArray(x.participants)?x.participants.slice(0,50).map(p=>({id:str(p.id,80),name:str(p.name,100),kind:str(p.kind,20),initiative:Math.max(-99,Math.min(999,Number(p.initiative)||0)),hp:num(p.hp,99999),hpMax:num(p.hpMax,99999),vd:num(p.vd,9999),defense:num(p.defense,999),sourceId:str(p.sourceId,80)})).filter(p=>p.id&&p.name):[]})).filter(x=>x.id&&x.title):[];
 const operationEntries=key=>Array.isArray(key)?key.filter(x=>x&&x.private!==true).slice(0,100).map(x=>({id:str(x.id,80),title:str(x.title,120),body:str(x.body,10000),status:str(x.status,40),source:str(x.source,140),role:str(x.role,100),disposition:str(x.disposition,40),element:str(x.element,40),vd:num(x.vd,9999),when:str(x.when,60),reference:str(x.reference,500),documentType:str(x.documentType,60),institution:str(x.institution,120),issueDate:str(x.issueDate,40),signature:str(x.signature,100),stamp:str(x.stamp,80),style:['ordem','jornal','carta','prontuario','policial','confidencial'].includes(x.style)?x.style:'ordem',image:/^data:image\/jpeg;base64,[A-Za-z0-9+/=]{1,32000}$/.test(String(x.image||''))?String(x.image):'',isProp:!!x.isProp,operationId:str(x.operationId,80),created:str(x.created,40)})).filter(x=>x.id&&x.title):[];
 const operations=Array.isArray(value.operations)?value.operations.slice(0,100).map(o=>({
  id:str(o.id,80),title:str(o.title,120),code:str(o.code,40),location:str(o.location,160),date:str(o.date,40),risk:str(o.risk,40),status:str(o.status,40),master:str(o.master,80),summary:str(o.summary,5000),
  agentIds:Array.isArray(o.agentIds)?o.agentIds.slice(0,200).map(x=>str(x,100)).filter(Boolean):[],
  crew:Array.isArray(o.crew)?o.crew.slice(0,200).map(x=>({id:str(x.id,100),name:str(x.name,100),meta:str(x.meta,100)})).filter(x=>x.id&&x.name):[],
  objectives:Array.isArray(o.objectives)?o.objectives.slice(0,200).map(x=>({id:str(x.id,80),text:str(x.text,300),done:!!x.done})).filter(x=>x.id&&x.text):[],
  clues:operationEntries(o.clues),npcs:operationEntries(o.npcs),creatures:operationEntries(o.creatures),documents:operationEntries(o.documents),timeline:operationEntries(o.timeline)
 })).filter(o=>o.id&&o.title):[];
 const clueStatuses=['Não analisada','Suspeita','Confirmada','Falsa','Resolvida','Analisada','Descartada'];
 const clues=Array.isArray(value.clues)?value.clues.slice(0,500).map(x=>({id:str(x.id,80),title:str(x.title,120),type:str(x.type,60),description:str(x.description,5000),location:str(x.location,160),foundBy:str(x.foundBy,120),foundAt:str(x.foundAt,40),operationId:str(x.operationId,80),status:clueStatuses.includes(x.status)?x.status:'Não analisada'})).filter(x=>x.id&&x.title):[];
 const muralKinds=['Pessoa','Local','Criatura','Documento','Ritual','Evento','Objeto'];
 const sanitizeBoard=input=>{const source=input&&typeof input==='object'?input:{},ids=new Set(),linksSeen=new Set();const cards=Array.isArray(source.cards)?source.cards.slice(0,120).filter(x=>x&&x.secret!==true&&x.visibility!=='secret').map(x=>{const kind=muralKinds.includes(x.kind)?x.kind:'Objeto',refKind=kind==='Pessoa'&&x.refKind==='agent'?'agent':kind==='Criatura'&&x.refKind==='threat'?'threat':'';return{id:str(x.id,80),title:str(x.title,120),kind,body:str(x.body,5000),x:Math.max(-1e12,Math.min(1e12,Math.round(Number(x.x)||0))),y:Math.max(-1e12,Math.min(1e12,Math.round(Number(x.y)||0))),refKind,refId:refKind?str(x.refId,80):'',refName:refKind?str(x.refName,120):''};}).filter(x=>{if(!x.id||!x.title||ids.has(x.id))return false;ids.add(x.id);return true;}):[];const links=Array.isArray(source.links)?source.links.slice(0,300).filter(x=>x&&x.secret!==true&&x.visibility!=='secret').map(x=>({id:str(x.id,80),from:str(x.from,80),to:str(x.to,80),relation:str(x.relation,160)})).filter(x=>x.id&&x.from&&x.to&&x.from!==x.to&&x.relation&&ids.has(x.from)&&ids.has(x.to)&&!linksSeen.has(x.id)&&linksSeen.add(x.id)):[];return{cards,links};};
 const legacy=value.mural&&typeof value.mural==='object'?value.mural:{},mural={...sanitizeBoard(legacy),title:str(legacy.title,120),description:str(legacy.description,500),deleted:legacy.deleted===true};
 const boardIds=new Set(),murals=Array.isArray(value.murals)?value.murals.slice(0,60).map(x=>({id:str(x?.id,80),title:str(x?.title,120),description:str(x?.description,500),...sanitizeBoard(x)})).filter(x=>x.id&&x.id!=='mural-inicial'&&x.title&&!boardIds.has(x.id)&&boardIds.add(x.id)):[];
 const mapKinds=['clue','hazard','death','npc','creature','document'];
 const maps=Array.isArray(value.maps)?value.maps.slice(0,6).map(m=>{const seen=new Set(),markers=Array.isArray(m?.markers)?m.markers.slice(0,150).filter(x=>x&&x.private!==true).map(x=>({id:str(x.id,80),kind:mapKinds.includes(x.kind)?x.kind:'clue',label:str(x.label,80),description:str(x.description,800),x:Math.max(0,Math.min(100,Number(x.x)||0)),y:Math.max(0,Math.min(100,Number(x.y)||0))})).filter(x=>x.id&&x.label&&!seen.has(x.id)&&seen.add(x.id)):[];return{id:str(m?.id,80),title:str(m?.title,100),location:str(m?.location,160),description:str(m?.description,1000),operationId:str(m?.operationId,80),image:/^data:image\/jpeg;base64,[A-Za-z0-9+/=]{1,100000}$/.test(String(m?.image||''))?String(m.image):'',markers};}).filter(m=>m.id&&m.title&&m.image):[];
 const npcs=Array.isArray(value.npcs)?value.npcs.slice(0,300).map(x=>({id:str(x.id,80),name:str(x.name,100),appearance:str(x.appearance,1200),profession:str(x.profession,100),personality:str(x.personality,1200),relation:str(x.relation,1000),location:str(x.location,160),status:str(x.status,60),operationId:str(x.operationId,80)})).filter(x=>x.id&&x.name):[];
 const relationKinds=['Aliado','Inimigo','Família','Funcionário','Culto','Suspeito','Parceiro','Conhecido','Personalizado'];
 const relationships=Array.isArray(value.relationships)?value.relationships.slice(0,600).filter(x=>x&&x.private!==true).map(x=>({id:str(x.id,80),from:str(x.from,100),to:str(x.to,100),kind:relationKinds.includes(x.kind)?x.kind:'Personalizado',label:str(x.label,100),note:str(x.note,1000)})).filter(x=>x.id&&x.from&&x.to&&x.from!==x.to):[];
 const relationshipPositions={};if(value.relationshipPositions&&typeof value.relationshipPositions==='object')for(const [id,pos] of Object.entries(value.relationshipPositions).slice(0,500)){relationshipPositions[str(id,100)]={x:Math.max(0,Math.min(100,Number(pos?.x)||0)),y:Math.max(0,Math.min(100,Number(pos?.y)||0))};}
 const secretMessages=Array.isArray(value.secretMessages)?value.secretMessages.slice(-120).map(x=>({id:str(x.id,80),author:str(x.author,60),created:str(x.created,40),iv:/^[A-Za-z0-9+/=]{16,32}$/.test(String(x.iv||''))?String(x.iv):'',ciphertext:/^[A-Za-z0-9+/=]{16,15000}$/.test(String(x.ciphertext||''))?String(x.ciphertext):'',keys:Array.isArray(x.keys)?x.keys.slice(0,51).map(k=>({wrappedKey:/^[A-Za-z0-9+/=]{300,3000}$/.test(String(k.wrappedKey||''))?String(k.wrappedKey):''})).filter(k=>k.wrappedKey):[]})).filter(x=>x.id&&x.iv&&x.ciphertext&&x.keys.length):[];
 const name=str(value.name,100);if(!name)return null;
 return{name,skin:["padrao","arquivo","sangue","morte","conhecimento","energia","medo","terminal","dossie","vhs","corrompido","morto"].includes(value.skin)?value.skin:"padrao",mode:str(value.mode,60),session:Math.max(1,Math.min(9999,Math.trunc(Number(value.session)||1))),status:str(value.status,40),notes:str(value.notes,20000),roster,combats:entries('combats',30),investigations:entries('investigations',50),reports:entries('reports',50),dice:entries('dice',80),annotations:entries('annotations',50),operations,documents:operationEntries(value.documents),clues,mural,murals,maps,npcs,relationships,relationshipPositions,secretMessages,messageMasterPublicKey:sanitizePublicKey(value.messageMasterPublicKey)};
}
async function sharedRoute(request,env,path,url){if(!env.DB)return response({error:'Mesa indisponível.'},503);if(request.method!=='GET'&&request.headers.get('Origin')!==url.origin)return response({error:'Origem inválida.'},403);const match=path.match(/^\/api\/shared\/([A-F0-9]{20})$/);if(path==='/api/shared'&&request.method==='POST'){const raw=await request.text();if(raw.length>1000000)return response({error:'Campanha muito grande.'},413);const campaign=sharedData(JSON.parse(raw));if(!campaign)return response({error:'Informe o nome da campanha.'},400);const payload=JSON.stringify(campaign);if(payload.length>1000000)return response({error:'Campanha muito grande.'},413);const code=crypto.randomUUID().replace(/-/g,'').slice(0,20).toUpperCase();await env.DB.prepare('INSERT INTO shared_campaigns (code,payload,revision) VALUES (?,?,1)').bind(code,payload).run();return response({code,campaign,revision:1},201);}if(!match)return response({error:'Mesa não encontrada.'},404);const code=match[1],row=await env.DB.prepare('SELECT payload, revision FROM shared_campaigns WHERE code = ?').bind(code).first();if(!row)return response({error:'Convite não encontrado. Confira o código.'},404);if(request.method==='GET')return response({code,campaign:JSON.parse(row.payload),revision:row.revision});if(request.method==='PUT'){const raw=await request.text();if(raw.length>1000000)return response({error:'Campanha muito grande.'},413);const input=JSON.parse(raw),campaign=sharedData(input.campaign);if(!campaign||!Number.isInteger(input.revision))return response({error:'Dados inválidos.'},400);const payload=JSON.stringify(campaign);if(payload.length>1000000)return response({error:'Campanha muito grande.'},413);const result=await env.DB.prepare('UPDATE shared_campaigns SET payload = ?, revision = revision + 1 WHERE code = ? AND revision = ?').bind(payload,code,input.revision).run();if(result.meta.changes!==1)return response({error:'A mesa mudou em outra tela. Atualize antes de salvar.'},409);return response({code,campaign,revision:input.revision+1});}return response({error:'Método inválido.'},405);}
export function handler(){return {async fetch(request,env){const url=new URL(request.url),path=url.pathname;try{if(path.startsWith('/api/')&&env.DB)await ensureSchema(env);if(!path.startsWith('/api/')){if(path==='/catalog.json'||path==='/catalog-public.json')return new Response('Não encontrado',{status:404});if(!env.ASSETS)return new Response('Site indisponível',{status:503});return env.ASSETS.fetch(request);}if(path==='/api/shared'||path.startsWith('/api/shared/'))return await sharedRoute(request,env,path,url);if(path==='/api/catalog'&&request.method==='GET'&&!request.headers.get('oai-authenticated-user-id')){if(!env.ASSETS)return response({error:'Catálogo indisponível.'},503);const asset=await env.ASSETS.fetch(new URL('/catalog-public.json',url));return asset.ok?new Response(asset.body,{headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'public, max-age=3600','X-Content-Type-Options':'nosniff'}}):response({error:'Catálogo indisponível.'},503);}const user=request.headers.get('oai-authenticated-user-id');if(!user)return response({error:'Entre na sua conta para acessar o arquivo.'},401);if(!env.DB||!env.FILES)return response({error:'Armazenamento indisponível. Tente novamente.'},503);if(!['GET','HEAD'].includes(request.method)&&request.headers.get('Origin')!==url.origin)return response({error:'Origem inválida.'},403);
if(path==='/api/catalog'&&request.method==='GET'){if(!env.ASSETS)return response({error:'Catálogo indisponível.'},503);const asset=await env.ASSETS.fetch(new URL('/catalog.json',url));return asset.ok?new Response(asset.body,{headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, max-age=3600','X-Content-Type-Options':'nosniff'}}):response({error:'Catálogo indisponível.'},503);}
if(path==='/api/state'){if(request.method==='GET'){const row=await env.DB.prepare('SELECT payload, revision FROM archives WHERE user_id = ?').bind(user).first();return response(row?{state:JSON.parse(row.payload),revision:row.revision}:{state:null,revision:0});}if(request.method==='PUT'){const raw=await request.text();if(raw.length>5000000)return response({error:'Arquivo muito grande.'},413);const data=JSON.parse(raw);if(!data.state||!Array.isArray(data.state.agents)||!Array.isArray(data.state.campaigns)||!Array.isArray(data.state.rolls)||!Number.isInteger(data.revision)||data.state.agents.length>300)return response({error:'Dados inválidos.'},400);const payload=JSON.stringify(data.state);let result;if(data.revision===0){result=await env.DB.prepare('INSERT INTO archives (user_id,payload,revision) VALUES (?,?,1) ON CONFLICT(user_id) DO NOTHING').bind(user,payload).run();}else{result=await env.DB.prepare('UPDATE archives SET payload = ?, revision = revision + 1 WHERE user_id = ? AND revision = ?').bind(payload,user,data.revision).run();}if(result.meta.changes!==1)return response({error:'O arquivo foi alterado em outra aba. Exporte as alterações e recarregue antes de continuar.'},409);return response({revision:data.revision+1});}}
if(path==='/api/books'&&request.method==='GET'){const rows=await env.DB.prepare('SELECT book_key, name FROM books WHERE user_id = ?').bind(user).all();return response(Object.fromEntries(rows.results.map(r=>[r.book_key,{name:r.name}])));}
if(path.includes('/multipart')){const result=await multipartBook(request,env,path,user);if(result)return result;}
const match=path.match(/^\/api\/books\/(base|horror|as[1-7])$/);if(match){const key=match[1],id=user+':'+key;const old=await env.DB.prepare('SELECT object_key, name FROM books WHERE id = ? AND user_id = ?').bind(id,user).first();if(request.method==='GET'){if(!old)return response({error:'PDF não encontrado.'},404);const obj=await env.FILES.get(old.object_key);if(!obj)return response({error:'PDF indisponível.'},404);return new Response(obj.body,{headers:{'Content-Type':'application/pdf','Content-Disposition':"inline; filename*=UTF-8''"+encodeURIComponent(old.name),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}if(request.method==='PUT'){const size=Number(request.headers.get('content-length'));if(!size||size>90*1024*1024)return response({error:'Escolha um PDF de até 90 MB.'},413);if(request.headers.get('content-type')!=='application/pdf')return response({error:'Envie um PDF.'},400);const name=decodeURIComponent(request.headers.get('x-file-name')||'livro.pdf').slice(0,200);const objectKey=user+'/'+crypto.randomUUID()+'.pdf';await env.FILES.put(objectKey,request.body,{httpMetadata:{contentType:'application/pdf'}});try{await env.DB.prepare('INSERT INTO books (id,user_id,book_key,name,object_key) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name = excluded.name, object_key = excluded.object_key').bind(id,user,key,name,objectKey).run();}catch(e){await env.FILES.delete(objectKey);throw e;}if(old)await env.FILES.delete(old.object_key);return response({name});}if(request.method==='DELETE'){await env.DB.prepare('DELETE FROM books WHERE id = ? AND user_id = ?').bind(id,user).run();if(old)await env.FILES.delete(old.object_key);return response({ok:true});}}
return response({error:'Rota não encontrada.'},404);
}catch(error){console.error('Limiar request failed',path,error.message);return response({error:'Não foi possível concluir. Seus dados na tela foram preservados; tente novamente.'},500);}}};}
