// Structured threat sheets. Official records stay read-only; copies belong to the user.
let threatDetailTab='status',threatElement='',threatLastRoll=null;
const threatAll=()=>[...officialThreats,...state.threats,...state.homebrew.filter(x=>x.type==='Ameaças')];
const threatById=id=>threatAll().find(x=>x.id===id);
const threatValue=v=>v===0?'0':esc(v??'—');
const thButton=(text,action,attrs='',cls='ghost')=>`<button type="button" class="button small ${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const thSign=n=>Number(n)>=0?'+'+Number(n):String(n);
const thTest=s=>`${s.dice??1}d20${thSign(s.bonus||0)}`;
const thProse=s=>String(s||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p).replace(/\n/g,'<br>')}</p>`).join('');
function thNormal(raw){
 const x={...raw};x.attrs=x.attrs||Object.fromEntries(['AGI','FOR','INT','PRE','VIG'].map((k,i)=>[k,x[['agility','strength','intellect','presence','vigor'][i]]??null]));
 x.skills=(x.skills||[]).map(s=>{const m=String(s.roll||'').match(/(\d+)d20\s*([+-]\d+)?/i);return {...s,dice:s.dice??(m?+m[1]:null),bonus:s.bonus??(m?+(m[2]||0):0)};});
 x.powers=Array.isArray(x.powers)?x.powers:[];
 if(!Array.isArray(x.actions)){x.actions=typeof x.actions==='string'&&x.actions.trim()?[{name:'Ações registradas',kind:'Ação',description:x.actions,attacks:[]}]:[];for(const a of x.abilities||[]){const m=String(a.attack||'').match(/(\d+)d20\s*([+-]\d+)?/i),entry={name:a.name,kind:a.kind,description:a.description||'',attacks:a.damage||a.attack?[{name:a.name,notes:a.attack||'',dice:m?+m[1]:null,bonus:m?+(m[2]||0):0,count:1,crit:20,multiplier:2,damages:a.damage?[{formula:a.damage,type:a.damageType||''}]:[]}]:[]};(/Poder|Passiva/i.test(a.kind)?x.powers:x.actions).push(entry);}}
 return x;
}
function thArt(x,cls=''){return x.image?imageTag(x,cls):`<div class="th-no-art ${cls}" aria-label="Sem ilustração"><span>◇</span><small>${esc(x.kind||'AMEAÇA')}</small></div>`;}
function renderThreatArchive(){
 const selected=location.hash.split('/')[1];if(selected)return renderThreatDetail(decodeURIComponent(selected));
 const q=threatFilter.toLocaleLowerCase('pt-BR'),filtered=threatAll().filter(x=>(threatSource==='todos'||(threatSource==='oficiais'?!!x.source:!x.source))&&(!threatElement||x.element===threatElement)&&(x.name+' '+x.element+' '+(x.source||'')).toLocaleLowerCase('pt-BR').includes(q));
 return `<div class="th-archive">${pagehead('ARQUIVO / AMEAÇAS','Ameaças','',button('+ Criar ameaça','new-threat','primary'))}<div class="th-toolbar"><label class="field">Buscar<input id="threat-search" placeholder="Nome ou livro" value="${esc(threatFilter)}"></label><label class="field">Elemento<select id="th-element"><option value="">Todos os elementos</option>${['Sangue','Morte','Conhecimento','Energia','Medo','Realidade','Outro'].map(v=>`<option ${v===threatElement?'selected':''}>${v}</option>`).join('')}</select></label><div class="th-source">${[['todos','Todas'],['oficiais','Dos livros'],['mesa','Minha mesa']].map(([id,title])=>thButton(title,'threat-source',`data-value="${id}"`,threatSource===id?'primary':'ghost')).join('')}</div></div><div class="th-result-count">${filtered.length} ameaças</div><div class="th-catalog">${filtered.map(x=>`<a class="th-catalog-card panel" href="#ameacas/${encodeURIComponent(x.id)}"><div class="th-card-art" data-element="${esc(x.element)}">${thArt(x,'th-catalog-image')}<span class="th-vd">VD <b>${threatValue(x.vd)}</b></span></div><div class="th-card-info"><span class="eyebrow">${esc(x.element||'Outro')}</span><h2>${esc(x.name)}</h2><p>${esc(x.size||'—')} · ${esc(x.kind||'Criatura')}</p><div class="th-card-stats"><span>PV <b>${threatValue(x.pv)}</b></span><span>DEF <b>${threatValue(x.defense)}</b></span><span class="th-open">Abrir ficha ↗</span></div></div></a>`).join('')||'<div class="panel empty">Nenhuma ameaça encontrada.</div>'}</div></div>`;
}
function thRollButton(x,s,label){return s.dice==null?'<span>—</span>':thButton(`◇ ${thTest(s)}`,'th-test',`data-id="${esc(x.id)}" data-dice="${s.dice}" data-bonus="${s.bonus||0}" data-label="${esc(label)}"`);}
function thEntries(x,key,editable){return `<div class="th-section-heading"><h2>${key==='actions'?'Ações':'Poderes e características'}</h2>${editable?thButton('+ Adicionar','th-entry-edit',`data-id="${esc(x.id)}" data-key="${key}"`):''}</div>${x[key].length?x[key].map((a,i)=>`<details class="th-action" ${i===0?'open':''}><summary><span><small>${esc(a.kind||(key==='powers'?'Poder':'Ação'))}</small><strong>${esc(a.name)}</strong></span><span aria-hidden="true">⌄</span></summary><div class="th-action-body">${(a.attacks||[]).map((atk,j)=>`<div class="th-attack"><div class="th-attack-title"><strong>${esc(atk.name||'Ataque')}</strong><span>${esc(atk.range||'')}${atk.count>1?' · '+atk.count+' ataques':''}</span></div><div class="th-attack-rolls"><label>TESTE${thRollButton(x,atk,atk.name||a.name)}</label>${(atk.damages||[]).map((d,k)=>`<label>${esc(d.type||'DANO')}${thButton('◇ '+esc(d.formula),'th-damage',`data-id="${esc(x.id)}" data-key="${key}" data-entry="${i}" data-attack="${j}" data-damage="${k}"`)}</label>`).join('')}</div><div class="th-crit">Crítico ${atk.crit??20}/x${atk.multiplier??2}${(atk.damages||[]).length?thButton('Rolar crítico','th-damage',`data-id="${esc(x.id)}" data-key="${key}" data-entry="${i}" data-attack="${j}" data-damage="0" data-critical="1"`):''}</div>${atk.notes?`<p>${esc(atk.notes)}</p>`:''}</div>`).join('')}<div class="th-prose">${thProse(a.description)}</div>${editable?`<div class="th-entry-controls">${thButton('Editar','th-entry-edit',`data-id="${esc(x.id)}" data-key="${key}" data-index="${i}"`)}${thButton('Excluir','th-entry-delete',`data-id="${esc(x.id)}" data-key="${key}" data-index="${i}"`)}</div>`:''}</div></details>`).join(''):'<p class="hint">Nenhum registro nesta seção.</p>'}`;}
function renderThreatDetail(id){
 const raw=threatById(id);if(!raw)return '<div class="panel empty">Ameaça não encontrada. <a href="#ameacas">Voltar ao catálogo</a></div>';
 const x=thNormal(raw),editable=!raw.source,active=threatDetailTab;
 const info=[['Sentidos',x.senses],['Resistências',x.resistances],['Imunidades',x.immunities],['Vulnerabilidades',x.vulnerabilities]].filter(([,v])=>v);
 let content='';
 if(active==='status')content=`<div class="th-attributes">${Object.entries(x.attrs).map(([k,v])=>`<div><small>${k}</small><strong>${threatValue(v)}</strong>${v!=null?thButton('◇','th-test',`aria-label="Rolar ${k}" data-id="${esc(x.id)}" data-dice="${v}" data-bonus="0" data-label="${k}"`):''}</div>`).join('')}</div><div class="th-status-grid"><section><div class="th-section-heading"><h2>Perícias</h2></div><div class="th-skill-list">${x.skills.map(s=>`<div><span>${esc(s.name)}</span>${thRollButton(x,s,s.name)}</div>`).join('')||'<p class="hint">Nenhuma perícia registrada.</p>'}</div></section><section class="th-defenses"><div class="th-defense-row"><div><small>DEFESA</small><strong>${threatValue(x.defense)}</strong></div><div><small>DESLOCAMENTO</small><b>${threatValue(x.movement)}</b></div></div>${info.map(([k,v])=>`<div class="th-property"><h3>${k}</h3><p>${esc(v)}</p></div>`).join('')}${x.disturbingPresence?`<div class="th-presence"><h3>Presença perturbadora</h3><p>${esc(x.disturbingPresence)}</p>${/\d+d\d+/.test(x.disturbingPresence)?thButton('◇ Rolar dano mental','th-formula',`data-expression="${esc(x.disturbingPresence.match(/\d+d\d+(?:[+-]\d+)?/)[0])}" data-label="Presença perturbadora"`):''}</div>`:''}</section></div>`;
 if(active==='combate')content=thEntries(x,'actions',editable)+thEntries(x,'powers',editable);
 if(active==='descricao')content=`<h2>Descrição</h2><div class="th-prose">${thProse(x.description)||'<p class="hint">Nenhuma descrição registrada.</p>'}</div>${x.source?`<footer class="th-reference">${esc(x.source)} · página ${esc(x.page)}${x.sheetImage?` · <a href="${esc(x.sheetImage)}" target="_blank" rel="noopener">Consultar página original ↗</a>`:''}</footer>`:''}`;
 return `<div class="th-sheet"><a class="back-link" href="#ameacas">‹ Ameaças</a><header class="th-sheet-heading"><div><span class="eyebrow">${esc(x.element||'Outro')}${x.secondaryElement?' · '+esc(x.secondaryElement):''}</span><h1>${esc(x.name)}</h1><p>${esc(x.kind||'Criatura')} · ${esc(x.size||'—')}</p></div><div class="th-heading-actions">${editable?thButton('Editar ficha','edit-threat',`data-id="${esc(x.id)}"`):thButton('Criar cópia','th-copy',`data-id="${esc(x.id)}"`)}${thButton('Usar no combate','th-encounter',`data-id="${esc(x.id)}"`,'primary')}</div></header><div class="th-sheet-layout"><aside class="th-sidebar panel"><div class="th-sheet-art" data-element="${esc(x.element)}">${thArt(x,'th-sheet-image')}</div><div class="th-resource"><div><small>PONTOS DE VIDA</small><strong>${threatValue(x.pv)} <span>/ ${threatValue(x.pv)}</span></strong></div><span class="th-vd">VD <b>${threatValue(x.vd)}</b></span></div><div class="th-hp-line"></div><p class="hint th-instance-note">Os PV de cada criatura são controlados no combate da campanha.</p><div class="th-origin">${esc(x.source||'Criação da minha mesa')}${x.page?' · p. '+esc(x.page):''}</div></aside><main class="th-content panel"><div class="tabs th-tabs" role="tablist" aria-label="Ficha da ameaça">${[['status','Status'],['combate','Combate'],['descricao','Descrição']].map(([key,title])=>`<button type="button" role="tab" aria-selected="${key===active}" class="${key===active?'active':''}" data-action="th-tab" data-tab="${key}">${title}</button>`).join('')}</div><div class="th-tab-content" role="tabpanel">${content}</div></main></div><div id="th-roll-result" class="th-roll-result" role="status" aria-live="polite">${threatLastRoll?thRollResult():''}</div></div>`;
}
function thSkillFields(s={name:'',dice:1,bonus:0}){return `<div class="th-skill-edit">${field('skillName','Perícia',s.name,'text','required maxlength="80"')}${field('skillDice','d20',s.dice??1,'number','required min="0" max="30"')}${field('skillBonus','Bônus',s.bonus||0,'number','required min="-100" max="100"')}${thButton('×','th-row-remove','aria-label="Remover perícia"')}</div>`;}
function editThreatArchive(id){
 const raw=[...state.threats,...state.homebrew].find(x=>x.id===id),x=thNormal(raw||{id:uid(),name:'',element:'Sangue',kind:'Criatura',size:'Médio',vd:20,pv:30,defense:15,attrs:{AGI:1,FOR:1,INT:1,PRE:1,VIG:1},skills:['Percepção','Iniciativa','Fortitude','Reflexos','Vontade'].map(name=>({name,dice:1,bonus:0}))});
 modal(raw?'Editar ficha':'Criar ameaça',`<div class="form-grid">${field('name','Nome',x.name,'text','required maxlength="100"')}${photoField(x.image)}${select('element','Elemento',['Sangue','Morte','Conhecimento','Energia','Medo','Realidade','Outro'],x.element)}${field('secondaryElement','Elementos secundários',x.secondaryElement||'')}${select('kind','Tipo',['Criatura','Pessoa','Animal','Outro'],x.kind||'Criatura')}${select('size','Porte',['Minúsculo','Pequeno','Médio','Grande','Enorme','Colossal'],x.size||'Médio')}${field('vd','VD',x.vd??0,'number','required min="0" max="9999"')}${field('pv','PV máximo',x.pv??0,'number','required min="0" max="99999"')}${field('defense','Defesa',x.defense??0,'number','min="0" max="999"')}${field('movement','Deslocamento',x.movement||'','text','placeholder="9m / 6q"')}</div><h3>Atributos</h3><div class="th-attribute-edit">${Object.entries(x.attrs).map(([k,v])=>field(k,k,v??'','number','min="0" max="30"')).join('')}</div><h3>Perícias</h3><div id="th-skills-editor">${x.skills.map(thSkillFields).join('')}</div>${thButton('+ Perícia','th-skill-add')}<h3>Características</h3><div class="form-grid">${[['senses','Sentidos'],['resistances','Resistências'],['immunities','Imunidades'],['vulnerabilities','Vulnerabilidades'],['disturbingPresence','Presença perturbadora']].map(([k,label])=>field(k,label,x[k]||'')).join('')}<label class="field full">Descrição<textarea name="description" rows="5" maxlength="30000">${esc(x.description||'')}</textarea></label></div><p class="hint">Depois de salvar, adicione ataques e poderes na aba Combate.</p>`,f=>{
  const form=document.querySelector('#modalform');const skills=[...form.querySelectorAll('.th-skill-edit')].map(row=>({name:row.querySelector('[name="skillName"]').value.trim(),dice:+row.querySelector('[name="skillDice"]').value,bonus:+row.querySelector('[name="skillBonus"]').value}));
  for(const k of ['name','element','secondaryElement','kind','size','movement','senses','resistances','immunities','vulnerabilities','disturbingPresence','description'])x[k]=String(f.get(k)||'').trim();
  for(const k of ['vd','pv','defense'])x[k]=f.get(k)===''?null:+f.get(k);
  x.attrs=Object.fromEntries(Object.keys(x.attrs).map(k=>[k,f.get(k)===''?null:+f.get(k)]));x.skills=skills;x.schemaVersion=2;
  if(raw)Object.assign(raw,x);else state.threats.push(x);photo(f.get('imageFile'),raw||x);save();location.hash='ameacas/'+x.id;render();
 });
}
function thDamageFields(d={formula:'1d6',type:''}){return `<div class="th-damage-edit">${field('damageFormula','Dados de dano',d.formula,'text','required placeholder="2d6+3" maxlength="100"')}${field('damageType','Tipo de dano',d.type||'','text','placeholder="Corte, Sangue…" maxlength="100"')}${thButton('×','th-row-remove','aria-label="Remover dano"')}</div>`;}
function thAttackFields(a={name:'',range:'Corpo a corpo',count:1,dice:1,bonus:0,crit:20,multiplier:2,damages:[{formula:'1d6',type:''}]}){return `<fieldset class="th-attack-edit"><legend>Ataque</legend><div class="form-grid">${field('attackName','Nome',a.name||'','text','required maxlength="100"')}${field('attackRange','Alcance',a.range||'')}${field('attackCount','Quantidade de ataques',a.count||1,'number','required min="1" max="50"')}${field('attackDice','Dados do teste (d20)',a.dice??1,'number','required min="0" max="30"')}${field('attackBonus','Bônus do teste',a.bonus||0,'number','required min="-100" max="100"')}${field('attackCrit','Margem de crítico',a.crit??20,'number','required min="1" max="20"')}${field('attackMultiplier','Multiplicador de crítico',a.multiplier||2,'number','required min="1" max="10"')}${field('attackNotes','Observações',a.notes||'')}</div><div class="th-damages">${(a.damages||[]).map(thDamageFields).join('')}</div><div class="actions">${thButton('+ Dano adicional','th-damage-add')}${thButton('Remover ataque','th-attack-remove')}</div></fieldset>`;}
function thEditEntry(id,key,index){
 const raw=threatById(id);if(!raw||raw.source||!['actions','powers'].includes(key))return;const x=thNormal(raw),entry=x[key][index]||{name:'',kind:key==='powers'?'Poder':'Padrão',description:'',attacks:[]};
 modal(index==null?'Adicionar '+(key==='powers'?'poder':'ação'):'Editar '+entry.name,`<div class="form-grid">${field('entryName','Nome',entry.name,'text','required maxlength="150"')}${select('entryKind','Tipo',['Padrão','Movimento','Completa','Livre','Reação','Poder','Passiva','Ação'],entry.kind||'Poder')}<label class="field full">Descrição e regras<textarea name="entryDescription" rows="7" maxlength="20000">${esc(entry.description||'')}</textarea></label></div><h3>Ataques</h3><div id="th-attacks-editor">${(entry.attacks||[]).map(thAttackFields).join('')}</div>${thButton('+ Adicionar ataque','th-attack-add')}`,f=>{
  const attacks=[...document.querySelectorAll('#th-attacks-editor .th-attack-edit')].map(row=>{const val=k=>row.querySelector(`[name="${k}"]`).value;return {name:val('attackName').trim(),range:val('attackRange'),count:+val('attackCount'),dice:+val('attackDice'),bonus:+val('attackBonus'),crit:+val('attackCrit'),multiplier:+val('attackMultiplier'),notes:val('attackNotes'),damages:[...row.querySelectorAll('.th-damage-edit')].map(d=>{const formula=d.querySelector('[name="damageFormula"]').value.trim();thParseDamage(formula);return {formula,type:d.querySelector('[name="damageType"]').value.trim()};})};});
  const result={name:String(f.get('entryName')).trim(),kind:String(f.get('entryKind')),description:String(f.get('entryDescription')||''),attacks};if(index==null)x[key].push(result);else x[key][index]=result;Object.assign(raw,x);save();render();
 });
}
function thParseDamage(expression){
 const s=String(expression).replace(/\s/g,'').toLowerCase();if(!/^[+-]?(?:\d{1,3}d\d{1,4}|\d{1,5})(?:[+-](?:\d{1,3}d\d{1,4}|\d{1,5}))*$/.test(s))throw Error('Use dados como 2d6+3 ou 2d6+1d4+3.');
 return s.match(/[+-]?[^+-]+/g).map(token=>{const sign=token[0]==='-'?-1:1,term=token.replace(/^[+-]/,'');if(!term.includes('d'))return {sign,constant:+term};const [count,sides]=term.split('d').map(Number);if(count<1||count>100||sides<2||sides>1000)throw Error('Quantidade ou faces de dados fora do limite.');return {sign,count,sides};});
}
function thRollDamage(expression,multiplier=1,random=dice){const terms=thParseDamage(expression),rolls=[];let total=0;for(const t of terms){if(t.constant!==undefined){total+=t.sign*t.constant;continue;}const values=Array.from({length:t.count*multiplier},()=>random(t.sides));total+=t.sign*values.reduce((a,b)=>a+b,0);rolls.push(`${t.sign<0?'−':''}${t.count*multiplier}d${t.sides}: ${values.join(', ')}`);}return {total,detail:rolls.join(' · ')+(terms.some(t=>t.constant!==undefined)?' · modificadores incluídos':'')};}
function thRollTest(count,bonus,random=dice){count=Number(count);bonus=Number(bonus);if(!Number.isInteger(count)||count<0||count>30||!Number.isFinite(bonus))throw Error('Teste inválido.');const rolls=Array.from({length:count||2},()=>random(20)),chosen=count===0?Math.min(...rolls):Math.max(...rolls);return {total:chosen+bonus,detail:`[${rolls.join(', ')}] → ${count===0?'menor':'maior'} ${chosen} ${thSign(bonus)}`};}
function thRollResult(){return `<div><small>${esc(threatLastRoll.label)}</small><strong>${threatLastRoll.result}</strong><span>${esc(threatLastRoll.detail)}</span></div>${thButton('×','th-roll-close','aria-label="Fechar resultado"')}`;}
function thRecordRoll(label,result){const record={id:uid(),label,detail:result.detail,result:result.total};state.rolls.unshift(record);state.rolls=state.rolls.slice(0,40);threatLastRoll=record;save();const box=document.querySelector('#th-roll-result');if(box)box.innerHTML=thRollResult();else toast(`${label}: ${result.total}`);}
function thEncounter(id){
 const threat=threatById(id),campaigns=state.campaigns.filter(c=>c.isMaster!==false);if(!campaigns.length)return toast('Crie uma campanha como mestre para preparar um combate.');
 modal('Adicionar ao combate',`<p><strong>${esc(threat.name)}</strong> · PV ${threatValue(threat.pv)} · VD ${threatValue(threat.vd)}</p><label class="field">Campanha<select name="campaign" id="th-encounter-campaign">${campaigns.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><label class="field">Combate<select name="encounter" id="th-encounter-select"></select></label>${field('newEncounter','Nome para novo combate','','text','maxlength="120" placeholder="Se não houver combate ou quiser criar outro"')}${field('initiative','Iniciativa',0,'number','min="-99" max="999"')}`,f=>{
  const local=campaigns.find(c=>c.id===f.get('campaign'));if(!local)throw Error('Escolha uma campanha.');
  const current=local.shareCode&&activeShared===local.shareCode&&sharedCampaign?sharedCampaign:local,updated=structuredClone(current);updated.combats=updated.combats||[];
  const newName=String(f.get('newEncounter')||'').trim();let encounter=!newName&&updated.combats.find(c=>c.id===f.get('encounter'));
  if(!encounter){encounter={id:uid(),title:newName||'Novo combate',body:'',participants:[],round:1,turn:0,created:new Date().toLocaleDateString('pt-BR')};updated.combats.push(encounter);}
  encounter.participants=encounter.participants||[];encounter.participants.push({id:uid(),sourceId:id,kind:'threat',name:threat.name,initiative:+f.get('initiative'),hp:threat.pv||0,hpMax:threat.pv||0,vd:threat.vd||0,defense:threat.defense||0});
  activeCombatId=encounter.id;mesaTab='combats';if(local.shareCode&&activeShared===local.shareCode&&sharedCampaign)updateShared(updated,'patch:combats');else{local.combats=updated.combats;save();}location.hash='campanhas/'+(local.shareCode||local.id)+'/mesa';render();toast('Ameaça adicionada ao combate.');
 });
 const select=document.querySelector('#th-encounter-select'),campaign=document.querySelector('#th-encounter-campaign');const populate=()=>{const c=campaigns.find(x=>x.id===campaign.value),current=c.shareCode&&activeShared===c.shareCode&&sharedCampaign?sharedCampaign:c;select.innerHTML=`<option value="">Criar novo combate</option>${(current.combats||[]).map(v=>`<option value="${esc(v.id)}">${esc(v.title)}</option>`).join('')}`;};campaign.addEventListener('change',populate);populate();
}

document.addEventListener('change',e=>{if(e.target.id==='th-element'){threatElement=e.target.value;render();}});
document.addEventListener('click',event=>{
 const b=event.target.closest?.('[data-action]');if(!b||!b.dataset.action.startsWith('th-'))return;event.preventDefault();event.stopImmediatePropagation();const a=b.dataset.action,d=b.dataset;
 try{
 if(a==='th-tab'){threatDetailTab=d.tab;render();}
 if(a==='th-roll-close'){threatLastRoll=null;document.querySelector('#th-roll-result').innerHTML='';}
 if(a==='th-test')thRecordRoll(d.label,thRollTest(+d.dice,+d.bonus));
 if(a==='th-formula')thRecordRoll(d.label,thRollDamage(d.expression));
 if(a==='th-damage'){const x=thNormal(threatById(d.id)),atk=x[d.key][+d.entry].attacks[+d.attack],damage=atk.damages[+d.damage];thRecordRoll(`${atk.name} · ${damage.type||'dano'}${d.critical?' · crítico':''}`,thRollDamage(damage.formula,d.critical?atk.multiplier||2:1));}
 if(a==='th-copy'){const x=structuredClone(thNormal(threatById(d.id)));x.id=uid();x.name+=' (cópia)';x.originalSource=x.source;delete x.source;delete x.sheetImage;delete x.page;state.threats.push(x);save();location.hash='ameacas/'+x.id;render();toast('Cópia criada na sua mesa.');}
 if(a==='th-entry-edit')thEditEntry(d.id,d.key,d.index===undefined?null:+d.index);
 if(a==='th-entry-delete'){const raw=threatById(d.id);if(!raw||raw.source)return;if(confirm('Excluir este registro da sua ameaça?')){const x=thNormal(raw);x[d.key].splice(+d.index,1);Object.assign(raw,x);save();render();}}
 if(a==='th-skill-add')document.querySelector('#th-skills-editor').insertAdjacentHTML('beforeend',thSkillFields());
 if(a==='th-row-remove')b.closest('.th-skill-edit,.th-damage-edit')?.remove();
 if(a==='th-attack-add')document.querySelector('#th-attacks-editor').insertAdjacentHTML('beforeend',thAttackFields());
 if(a==='th-attack-remove')b.closest('.th-attack-edit').remove();
 if(a==='th-damage-add')b.closest('.th-attack-edit').querySelector('.th-damages').insertAdjacentHTML('beforeend',thDamageFields());
 if(a==='th-encounter')thEncounter(d.id);
 }catch(error){toast(error.message||'Não foi possível concluir.');}
},true);
